trigger: none

variables:
- group: terraform-aws-config

pool:
    vmImage: 'ubuntu-latest'

# Define steps     
steps:


# Install Terraform
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  displayName: install terraform
  inputs:
    terraformVersion: latest

# Terraform init
- task: TerraformCLI@0
  displayName: 'Terraform Init'
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/session5/'
    backendType: 'aws'
    backendServiceAws: $(backendServiceAWS)
    backendAwsRegion: $(backendAwsRegion)
    backendAwsBucket: '$(backendAwsBucket)'
    backendAwsKey: '$(backendAwsKey)'
  

# Terraform Validate
- task: TerraformCLI@0
  displayName: 'Terraform Validate'
  inputs:
    backendType: 'aws'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/session5/'
    backendServiceAWS: $(backendServiceAWS)

# Create artifact directory
- bash: |
      mkdir -p $(Pipeline.Workspace)/Output
  name: 'Directory'
  displayName: 'Create artifact directory'

# Terraform Plan
- task: TerraformCLI@0
  displayName: 'Terraform Plan'
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/session5/'
    commandOptions: '-out=$(Pipeline.Workspace)/Output/terraform.tfplan'
    publishPlanResults: 'terraform.tfplan'
    providerServiceAws: '$(providerServiceAws)'
    providerAwsRegion: 'eu-west-2'
    
    
# Publish Terraform Plan artifact
- task: PublishPipelineArtifact@1
  displayName: 'Publish plan artifact'
  inputs:
    targetPath: '$(Pipeline.Workspace)/Output'
    artifact: 'Evaluate'
    publishLocation: '$(providerServiceAws)'
    
# Apply Terraform Plan
- task: TerraformCLI@0
  displayName: 'Terraform Apply'
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/session5/'
    commandOptions: '$(Pipeline.Workspace)/Output/terraform.tfplan'
    providerServiceAws: '$(providerServiceAws)'
    providerAwsRegion: 'eu-west-2'    